# Generated by Django 5.2 on 2026-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0002_collection_organizer_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
