# Generated by Django 5.2 on 2026-01-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('split', '0003_alter_collection_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='amount_owed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
