# Generated by Django 5.1.4 on 2026-01-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("split", "0004_alter_contributor_amount_owed"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="magic_token",
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="magic_token_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="organizer_email",
            field=models.EmailField(max_length=254),
        ),
    ]
