# Generated by Django 5.1.4 on 2026-01-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("split", "0005_collection_magic_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="type",
            field=models.CharField(
                choices=[("manual", "Manual"), ("automatic", "Automatic")],
                default="manual",
                max_length=20,
            ),
        ),
    ]
